/**
 * Mock Data for Deal Room
 * Sample deals, templates, documents, and stakeholders
 */

import type {
	Deal,
	DealTemplate,
	DealDocument,
	DealStakeholder,
	DealChecklistTask,
	DealMilestone,
	DealComment,
} from "@/types/_dashboard/dealRoom";

// Sample Active Deals
export const sampleDeals: Deal[] = [
	{
		id: "deal-1",
		propertyAddress: "1234 Oak Street",
		propertyCity: "Austin",
		propertyState: "TX",
		propertyZip: "78701",
		propertyPhoto: "/images/properties/oak-street.jpg",
		dealType: "fix-and-flip",
		status: "due-diligence",
		purchasePrice: 285000,
		estimatedARV: 425000,
		projectedROI: 35,
		createdAt: "2024-11-15T10:00:00Z",
		updatedAt: "2024-12-01T14:30:00Z",
		closingDate: "2024-12-28T00:00:00Z",
		daysUntilClosing: 25,
		completionPercentage: 65,
		ownerId: "user-1",
		ownerName: "John Investor",
	},
	{
		id: "deal-2",
		propertyAddress: "567 Maple Avenue",
		propertyCity: "Portland",
		propertyState: "OR",
		propertyZip: "97201",
		propertyPhoto: "/images/properties/maple-ave.jpg",
		dealType: "single-family-rental",
		status: "under-contract",
		purchasePrice: 425000,
		estimatedARV: 480000,
		projectedROI: 8.5,
		createdAt: "2024-11-20T09:00:00Z",
		updatedAt: "2024-12-02T16:45:00Z",
		closingDate: "2025-01-15T00:00:00Z",
		daysUntilClosing: 43,
		completionPercentage: 45,
		ownerId: "user-1",
		ownerName: "John Investor",
	},
	{
		id: "deal-3",
		propertyAddress: "890 Pine Boulevard",
		propertyCity: "Denver",
		propertyState: "CO",
		propertyZip: "80202",
		propertyPhoto: "/images/properties/pine-blvd.jpg",
		dealType: "multi-family",
		status: "financing",
		purchasePrice: 1250000,
		estimatedARV: 1400000,
		projectedROI: 12,
		createdAt: "2024-10-05T11:00:00Z",
		updatedAt: "2024-12-03T09:20:00Z",
		closingDate: "2024-12-20T00:00:00Z",
		daysUntilClosing: 17,
		completionPercentage: 75,
		ownerId: "user-1",
		ownerName: "John Investor",
	},
];

// Deal Templates
export const dealTemplates: DealTemplate[] = [
	{
		id: "template-sfr",
		name: "Single-Family Rental",
		description: "Standard template for long-term rental properties",
		dealType: "single-family-rental",
		icon: "🏠",
		defaultFolders: [
			"property-info",
			"financials",
			"due-diligence",
			"legal",
			"financing",
			"closing",
			"post-closing",
		],
		defaultChecklist: [
			{
				title: "Order home inspection",
				category: "due-diligence",
				priority: "critical",
			},
			{
				title: "Review title report",
				category: "legal",
				priority: "high",
			},
			{
				title: "Analyze rent comps",
				category: "financials",
				priority: "high",
			},
			{
				title: "Calculate cash flow",
				category: "financials",
				priority: "medium",
			},
			{
				title: "Review HOA docs",
				category: "due-diligence",
				priority: "medium",
			},
			{
				title: "Get insurance quote",
				category: "financing",
				priority: "medium",
			},
		],
		defaultMilestones: [
			{
				title: "Offer Accepted",
				description: "Seller accepted purchase offer",
				date: "",
				type: "offer-accepted",
				isCriticalPath: true,
			},
			{
				title: "Inspection Contingency",
				description: "Home inspection must be completed",
				date: "",
				type: "inspection-due",
				isCriticalPath: true,
			},
			{
				title: "Financing Contingency",
				description: "Loan approval deadline",
				date: "",
				type: "financing-contingency",
				isCriticalPath: true,
			},
			{
				title: "Closing Date",
				description: "Final closing and transfer of ownership",
				date: "",
				type: "closing-date",
				isCriticalPath: true,
			},
		],
		estimatedDaysToClose: 45,
	},
	{
		id: "template-flip",
		name: "Fix & Flip",
		description: "Template for renovation and resale projects",
		dealType: "fix-and-flip",
		icon: "🔨",
		defaultFolders: [
			"property-info",
			"financials",
			"due-diligence",
			"legal",
			"financing",
			"closing",
		],
		defaultChecklist: [
			{
				title: "Get contractor estimates",
				category: "financials",
				priority: "critical",
			},
			{
				title: "Calculate ARV with comps",
				category: "financials",
				priority: "critical",
			},
			{
				title: "Order home inspection",
				category: "due-diligence",
				priority: "high",
			},
			{
				title: "Check permit requirements",
				category: "legal",
				priority: "high",
			},
			{
				title: "Secure hard money loan",
				category: "financing",
				priority: "high",
			},
		],
		defaultMilestones: [
			{
				title: "Offer Accepted",
				description: "Purchase offer accepted",
				date: "",
				type: "offer-accepted",
				isCriticalPath: true,
			},
			{
				title: "Inspection Complete",
				description: "Home inspection and contractor walkthrough",
				date: "",
				type: "inspection-due",
				isCriticalPath: true,
			},
			{
				title: "Financing Secured",
				description: "Hard money or cash funding confirmed",
				date: "",
				type: "financing-contingency",
				isCriticalPath: true,
			},
			{
				title: "Close & Begin Rehab",
				description: "Ownership transferred, renovations start",
				date: "",
				type: "closing-date",
				isCriticalPath: true,
			},
		],
		estimatedDaysToClose: 30,
	},
	{
		id: "template-wholesale",
		name: "Wholesale Deal",
		description: "Quick assignment template for wholesalers",
		dealType: "wholesale",
		icon: "⚡",
		defaultFolders: ["property-info", "financials", "legal", "closing"],
		defaultChecklist: [
			{
				title: "Get property under contract",
				category: "legal",
				priority: "critical",
			},
			{
				title: "Find end buyer",
				category: "property-info",
				priority: "critical",
			},
			{
				title: "Calculate assignment fee",
				category: "financials",
				priority: "high",
			},
			{
				title: "Draft assignment agreement",
				category: "legal",
				priority: "high",
			},
		],
		defaultMilestones: [
			{
				title: "Contract Signed",
				description: "Property under contract with seller",
				date: "",
				type: "offer-accepted",
				isCriticalPath: true,
			},
			{
				title: "Buyer Found",
				description: "End buyer identified and committed",
				date: "",
				type: "custom",
				isCriticalPath: true,
			},
			{
				title: "Assignment Complete",
				description: "Contract assigned and fee collected",
				date: "",
				type: "closing-date",
				isCriticalPath: true,
			},
		],
		estimatedDaysToClose: 14,
	},
	{
		id: "template-multifamily",
		name: "Multi-Family Property",
		description: "Template for apartment buildings and duplexes",
		dealType: "multi-family",
		icon: "🏢",
		defaultFolders: [
			"property-info",
			"financials",
			"due-diligence",
			"legal",
			"financing",
			"closing",
			"post-closing",
		],
		defaultChecklist: [
			{
				title: "Review rent rolls (12 months)",
				category: "financials",
				priority: "critical",
			},
			{
				title: "Analyze operating expenses",
				category: "financials",
				priority: "critical",
			},
			{
				title: "Inspect all units",
				category: "due-diligence",
				priority: "high",
			},
			{
				title: "Review tenant leases",
				category: "legal",
				priority: "high",
			},
			{
				title: "Check city/county regulations",
				category: "legal",
				priority: "medium",
			},
			{
				title: "Secure commercial financing",
				category: "financing",
				priority: "high",
			},
		],
		defaultMilestones: [
			{
				title: "LOI Accepted",
				description: "Letter of intent accepted by seller",
				date: "",
				type: "offer-accepted",
				isCriticalPath: true,
			},
			{
				title: "Due Diligence Period",
				description: "Review financials and inspect property",
				date: "",
				type: "inspection-due",
				isCriticalPath: true,
			},
			{
				title: "Loan Commitment",
				description: "Commercial loan approved",
				date: "",
				type: "financing-contingency",
				isCriticalPath: true,
			},
			{
				title: "Closing",
				description: "Final closing and property transfer",
				date: "",
				type: "closing-date",
				isCriticalPath: true,
			},
		],
		estimatedDaysToClose: 60,
	},
];

// Sample Documents for Deal 1
export const sampleDocuments: DealDocument[] = [
	{
		id: "doc-1",
		dealId: "deal-1",
		name: "MLS Listing Sheet.pdf",
		category: "property-info",
		fileUrl: "/documents/mls-listing.pdf",
		fileSize: 245600,
		fileType: "application/pdf",
		uploadedBy: "John Investor",
		uploadedAt: "2024-11-15T10:30:00Z",
		version: 1,
		viewCount: 8,
		downloadCount: 3,
		lastViewedAt: "2024-12-01T09:15:00Z",
	},
	{
		id: "doc-2",
		dealId: "deal-1",
		name: "Home Inspection Report.pdf",
		category: "due-diligence",
		fileUrl: "/documents/inspection-report.pdf",
		fileSize: 1240000,
		fileType: "application/pdf",
		uploadedBy: "Inspector Services",
		uploadedAt: "2024-11-22T14:00:00Z",
		version: 1,
		viewCount: 12,
		downloadCount: 5,
		lastViewedAt: "2024-11-30T11:20:00Z",
	},
	{
		id: "doc-3",
		dealId: "deal-1",
		name: "Purchase Agreement.pdf",
		category: "legal",
		fileUrl: "/documents/purchase-agreement.pdf",
		fileSize: 580000,
		fileType: "application/pdf",
		uploadedBy: "Title Company",
		uploadedAt: "2024-11-16T16:45:00Z",
		version: 2,
		isWatermarked: true,
		viewCount: 15,
		downloadCount: 4,
		lastViewedAt: "2024-12-02T08:30:00Z",
	},
];

// Sample Stakeholders for Deal 1
export const sampleStakeholders: DealStakeholder[] = [
	{
		id: "stake-1",
		dealId: "deal-1",
		name: "John Investor",
		email: "john@example.com",
		phone: "555-0100",
		role: "buyer",
		permissionLevel: "owner",
		addedAt: "2024-11-15T10:00:00Z",
		lastActive: "2024-12-03T09:00:00Z",
	},
	{
		id: "stake-2",
		dealId: "deal-1",
		name: "Sarah Martinez",
		email: "sarah@realty.com",
		phone: "555-0101",
		role: "agent",
		company: "Premier Realty",
		permissionLevel: "editor",
		addedAt: "2024-11-15T10:15:00Z",
		lastActive: "2024-12-02T15:30:00Z",
	},
	{
		id: "stake-3",
		dealId: "deal-1",
		name: "Mike Thompson",
		email: "mike@titleco.com",
		phone: "555-0102",
		role: "title-company",
		company: "Secure Title Co",
		permissionLevel: "editor",
		addedAt: "2024-11-16T11:00:00Z",
		lastActive: "2024-12-01T10:45:00Z",
	},
	{
		id: "stake-4",
		dealId: "deal-1",
		name: "Lisa Chen",
		email: "lisa@bankcorp.com",
		phone: "555-0103",
		role: "lender",
		company: "First National Bank",
		permissionLevel: "viewer",
		addedAt: "2024-11-18T14:00:00Z",
		lastActive: "2024-11-29T13:20:00Z",
	},
];

// Sample Checklist Tasks for Deal 1
export const sampleChecklistTasks: DealChecklistTask[] = [
	{
		id: "task-1",
		dealId: "deal-1",
		title: "Order home inspection",
		description: "Schedule professional home inspection within 10 days",
		category: "due-diligence",
		isCompleted: true,
		completedAt: "2024-11-22T14:00:00Z",
		completedBy: "John Investor",
		dueDate: "2024-11-25T00:00:00Z",
		assignedTo: "John Investor",
		priority: "critical",
		relatedDocumentId: "doc-2",
	},
	{
		id: "task-2",
		dealId: "deal-1",
		title: "Review title report",
		description: "Examine title for liens or encumbrances",
		category: "legal",
		isCompleted: true,
		completedAt: "2024-11-20T10:30:00Z",
		completedBy: "Mike Thompson",
		dueDate: "2024-11-23T00:00:00Z",
		assignedTo: "Mike Thompson",
		priority: "critical",
	},
	{
		id: "task-3",
		dealId: "deal-1",
		title: "Get contractor estimates",
		description: "Obtain 3 repair estimates for rehab work",
		category: "financials",
		isCompleted: true,
		completedAt: "2024-11-28T16:00:00Z",
		completedBy: "John Investor",
		dueDate: "2024-11-30T00:00:00Z",
		assignedTo: "John Investor",
		priority: "high",
	},
	{
		id: "task-4",
		dealId: "deal-1",
		title: "Secure financing approval",
		description: "Finalize loan approval and terms",
		category: "financing",
		isCompleted: false,
		dueDate: "2024-12-10T00:00:00Z",
		assignedTo: "Lisa Chen",
		priority: "critical",
	},
	{
		id: "task-5",
		dealId: "deal-1",
		title: "Order appraisal",
		description: "Schedule property appraisal for lender",
		category: "due-diligence",
		isCompleted: false,
		dueDate: "2024-12-08T00:00:00Z",
		assignedTo: "Lisa Chen",
		priority: "high",
	},
	{
		id: "task-6",
		dealId: "deal-1",
		title: "Final walkthrough",
		description: "Inspect property before closing",
		category: "closing",
		isCompleted: false,
		dueDate: "2024-12-27T00:00:00Z",
		assignedTo: "John Investor",
		priority: "high",
	},
];

// Sample Milestones for Deal 1
export const sampleMilestones: DealMilestone[] = [
	{
		id: "mile-1",
		dealId: "deal-1",
		title: "Offer Accepted",
		description: "Seller accepted our purchase offer of $285,000",
		date: "2024-11-15T00:00:00Z",
		isCompleted: true,
		completedAt: "2024-11-15T16:30:00Z",
		type: "offer-accepted",
		isCriticalPath: true,
	},
	{
		id: "mile-2",
		dealId: "deal-1",
		title: "Inspection Contingency",
		description: "Home inspection must be completed by this date",
		date: "2024-11-25T00:00:00Z",
		isCompleted: true,
		completedAt: "2024-11-22T14:30:00Z",
		type: "inspection-due",
		isCriticalPath: true,
	},
	{
		id: "mile-3",
		dealId: "deal-1",
		title: "Financing Contingency",
		description: "Loan approval deadline",
		date: "2024-12-10T00:00:00Z",
		isCompleted: false,
		type: "financing-contingency",
		isCriticalPath: true,
	},
	{
		id: "mile-4",
		dealId: "deal-1",
		title: "Appraisal Due",
		description: "Property appraisal must be completed",
		date: "2024-12-08T00:00:00Z",
		isCompleted: false,
		type: "appraisal-due",
		isCriticalPath: false,
	},
	{
		id: "mile-5",
		dealId: "deal-1",
		title: "Closing Date",
		description: "Final closing at title company",
		date: "2024-12-28T00:00:00Z",
		isCompleted: false,
		type: "closing-date",
		isCriticalPath: true,
	},
];

// Sample Comments for Deal 1
export const sampleComments: DealComment[] = [
	{
		id: "comment-1",
		dealId: "deal-1",
		content:
			"Home inspection revealed some minor roof issues. Contractor estimates $8,500 for repairs. Should we negotiate this with seller?",
		authorId: "user-1",
		authorName: "John Investor",
		createdAt: "2024-11-23T09:30:00Z",
		mentions: ["stake-2"],
	},
	{
		id: "comment-2",
		dealId: "deal-1",
		content:
			"@Sarah Martinez - I've reached out to the seller's agent. They're willing to credit $5,000 at closing for the roof repairs. Good compromise!",
		authorId: "stake-2",
		authorName: "Sarah Martinez",
		createdAt: "2024-11-23T14:45:00Z",
		parentCommentId: "comment-1",
		mentions: ["user-1"],
	},
	{
		id: "comment-3",
		dealId: "deal-1",
		content:
			"Title is clean, no liens or encumbrances found. We're good to proceed. Title insurance quote attached.",
		authorId: "stake-3",
		authorName: "Mike Thompson",
		createdAt: "2024-11-20T11:00:00Z",
		attachments: ["doc-3"],
	},
];

