export const CITIES_BY_STATE: Record<string, string[]> = {
	CA: [
		"Los Angeles",
		"San Diego",
		"San Jose",
		"San Francisco",
		"Fresno",
		"Sacramento",
	],
	TX: ["Houston", "San Antonio", "Dallas", "Austin", "Fort Worth", "El Paso"],
	FL: [
		"Jacksonville",
		"Miami",
		"Tampa",
		"Orlando",
		"St. Petersburg",
		"Hialeah",
	],
	NY: ["New York", "Buffalo", "Rochester", "Yonkers", "Syracuse", "Albany"],
	IL: ["Chicago", "Aurora", "Naperville", "Joliet", "Rockford", "Springfield"],
	AZ: ["Phoenix", "Tucson", "Mesa", "Chandler", "Glendale", "Scottsdale"],
	PA: [
		"Philadelphia",
		"Pittsburgh",
		"Allentown",
		"Erie",
		"Reading",
		"Scranton",
	],
	OH: ["Columbus", "Cleveland", "Cincinnati", "Toledo", "Akron", "Dayton"],
	GA: ["Atlanta", "Augusta", "Columbus", "Savannah", "Athens", "Sandy Springs"],
	NC: [
		"Charlotte",
		"Raleigh",
		"Greensboro",
		"Durham",
		"Winston-Salem",
		"Fayetteville",
	],
};
